### ISSUE TITLE
Hackage version has out-of-date version bounds on vector-space

### ISSUE THREAD

**Issue by RyanGlScott** [diagrams/active#12]
I'm having trouble building `diagrams` packages from Hackage at the moment since the version of `active` on Hackage requires `vector-space == 0.8`, but the latest version is `0.9`. The [`active-0.1`](https://github.com/diagrams/active/tree/active-0.1) branch has this fixed—can you release it to Hackage?

**Comment by andygill** [comment]
Ryan,

Are you around later today in ITTC? If so, we’ll coordinate this and other updates.

Andy

**Comment by RyanGlScott** [comment]
[`active-0.1.0.18`](http://hackage.haskell.org/package/active-0.1.0.18) was just released on Hackage, so this is resolved.
