### ISSUE TITLE
Test suite weirdness on arm64 and s390x

### ISSUE THREAD

**Issue by nomeata** [diagrams/active#15]
Hi,

I observe test failures on arm64 and s390x:
https://buildd.debian.org/status/fetch.php?pkg=haskell-active&arch=arm64&ver=0.2.0.4-1&stamp=1442017124
https://buildd.debian.org/status/fetch.php?pkg=haskell-active&arch=s390x&ver=0.2.0.4-1&stamp=1442020102
while the test suite goes through on other, similar architectures, including mipsel, powerpc and powerpc64, so there is no obvious pattern here.

The build is killed with a timeout after 150 minutes – is there anything in the testsuite that can deadlock on a non-threaded runtime? (Hoping this is not just https://github.com/haskell/cabal/issues/2398 again, but then it would fail on other architectures with a non-threaded runtime, I’d say.)

**Comment by nomeata** [comment]
Probably not active-specific, I see this pattern also when building another package (esqueleto).

**Comment by byorgey** [comment]
OK, thanks for looking into it.  The active test suite is just a standard, pure, QuickCheck suite so I would be very surprised if it was something active-specific.
